# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('learn', ['core','network','point-to-point'])
    module.source = [
        'model/learn.cc',
        'helper/learn-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('learn')
    module_test.source = [
        'test/learn-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'learn'
    headers.source = [
        'model/learn.h',
        'helper/learn-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

